trigger:
- master

pool:
  name: windows-app-test
  demands:
   - agent.name -equals AWILBER-COMP

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      
      Write-Host "Hello World"