trigger: 
- main

pool:
  name: Default
   
jobs:
- deployment: VMDeploy
  displayName: Deploy to VM
  environment: 
   name: intune-automate
   resourceName: DESKTOP-BRD3B8T
   resourceType: virtualMachine
  strategy:
     runOnce:
        deploy:   
          steps:
            - script: echo "Hello world"